### ISSUE TITLE
Homepage: Event Records Attended by WEB3DEV

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/community-management#100]
- [ ] Upload all videos and photos of the events you attended to Google Drive.
- [ ] Organize current content

**Comment by annabida** [comment]
Put what you find here in the [Drive](https://drive.google.com/drive/folders/1XrR82en9cyXEAC78UV57pJyDRjxylaxY)
Create the folder with the following criteria: event name - country and city - month and year

**Comment by annabida** [comment]
We decided to remove from the scope
