### ISSUE TITLE
Interviews with contributing members of the community

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#117]
**Description:**
Conduct interviews with community members to gather insights on their experiences, contributions, and feedback for improving our processes.

**Checklist:**
- [x] Create interview script
- [x] Schedule interviews with 5 members
- [x] Conduct interviews
- [x] Analyze interview data
- [x] Summarize findings and provide recommendations

**Notes:**
- Ensure the interview script covers key aspects of onboarding, contributions, and offboarding.
- Schedule interviews at convenient times for the members.
- Record and document interviews for accurate data analysis.

**Comment by nomadbitcoin** [comment]
Are you talking with the contributors from Kyodo? William, 7Seven, Lucas...

**Comment by annabida** [comment]
@nomadbitcoin 
I haven't dialed them yet, could you confirm the username of Willian and Lucas on discord? 
I've just been chatting to 7Seven?

**Comment by annabida** [comment]
Document used in the interviews: https://docs.google.com/document/d/1Pvx-PNdXmSVKUdTzfLafrsmp4ioG7RUM4c06YgTkecQ/edit?usp=sharing

Date of interviews:
1. 14/May - Paulo Gio
2. 29/May - Rodrigo Serafim
3. 31/May - Jenny
4. 05/Jun - Judá
5. 07/Jun - Lucas
6. 07/Jun - Bruno
7. 17/Jun - 7even/Bruno
8. 17/Jun - Willian e Nosfera/Eduardo

**Comment by annabida** [comment]
# Feedback Analysis for WEB3DEV Community Processes

## Initial Experience
**Positives:**
- Information security and rewards.
- Freedom to adapt systems and improve processes.
- Full support from the Community Manager and other leaders.
- Organic and well-guided onboarding process.

**Challenges:**
- Volume of information and changes when assuming leadership.
- Insufficient and unclear documentation.
- Difficulty understanding functions of tools like Discord and GitHub.
- Need for centralized information.

## Orientation and Support
**Positives:**
- Comprehensive support in the early days, especially from leaders like André and Vini.
- Availability of members to answer questions and provide support.

**Challenges:**
- Lack of clarity on the responsibilities of each member.
- Need for improvements in communication channels, especially on Discord.
- Inadequate or inaccessible documentation.

## Documentation and Tools
**Positives:**
- GitHub is well organized and useful.
- Daily meetings helped with alignment and support.

**Challenges:**
- Need for tutorials, explanatory videos, and feedback meetings.
- Initial difficulty with platforms like GitHub and Discord.
- Lack of clear and accessible documentation for beginners.

## Contributions, Motivation, and Engagement
**Motivation:**
- Interest in learning and networking.
- Pursuit of reputation and knowledge.
- Contributions to innovative projects.

**Challenges:**
- Lack of financial opportunities.
- Poorly defined and communicated contribution processes.
- Difficulty finding and selecting tasks.
- Need for more clarity and documentation.

## Evaluation and Rewards
**Positives:**
- Recognition for the impact of contributions.
- Transparent reward process in some cases.

**Challenges:**
- Need for a more appropriate and tangible reward system.
- Lack of clarity about rewards and fair evaluation of contributions.

## Closing Activities and Off-boarding
**Positives:**
- Community willingness to support even after off-boarding.

**Challenges:**
- Need for objective communication without delays.
- Lack of adequate support or communication during closures.
- Lack of strategies to maintain contact with former members.

## General Suggestions
- Implement videos and documentation on GitHub.
- Conduct explanatory and feedback meetings.
- Create tutorials and FAQs to facilitate tool usage.
- Improve communication and engagement channels on Discord.
- Define clear processes for onboarding and contribution.
- Establish a more tangible and fair reward system.

These insights provide a detailed view of the strengths and areas for improvement, which can be used to enhance the member experience in the WEB3DEV community.

**Comment by annabida** [comment]
The results of this issue were presented at Retroplanning on June 21, 2024 in the presence of @marcaum-eth @nomadbitcoin
