### ISSUE TITLE
Homepage V2: Create Artwork with Photos of the Study Group Leaders page

### ISSUE THREAD

**Issue by marcaumdesign** [w3b3d3v/community-management#147]
## Description:

Design and create artwork featuring photos of the study group leaders to be showcased on the community homepage, highlighting their contributions and leadership.

- [x] Collect high-quality photos of the study group leaders.
- [x] Design the layout and style of the artwork to match the homepage aesthetics.
- [x] Remove background from photos
- [x] Incorporate the photos and create the artwork.
- [x] Review and revise the artwork for consistency and appeal.
- [x] Integrate the final artwork into the homepage.
- [x] Announce the update to the community and highlight the study group leaders.

> The photo updates are in the following folder: https://drive.google.com/drive/folders/1793O2FLUr8CRXyt5NiYHfGUX9r0NXKGr?usp=sharing

**Comment by marcaumdesign** [comment]
I made a pattern here where the group leader's face is the main focus and the background is the color of the determined course, despite it being simple, the photo icons won't be much larger than 200x200 throughout the interfaces, that is, add an artwork can be a work that does not compensate for the small size that will be shown.

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/b7926ac6-3561-4410-8a5b-bb5b18a8d2c4)

**Comment by annabida** [comment]
@marcaum-eth I think there was some noise in the communication.
The images of the leaders would be used as the main images of the study group, instead of the image with the group's title, because we want to give prominence to the leaders, both in recognition of the leader's contribution and to have a more humanized page with a community vibe.

**Comment by marcaumdesign** [comment]
oq acham dessa alternativa para fecharmos essa issue? @annabida @piadascripto @nomadbitcoin 

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/41453c62-31ab-4ff6-a085-28dcf6a8d33c)

**Comment by piadascripto** [comment]
Eu curto

**Comment by piadascripto** [comment]
inclusive, podemos usar esse padrão para as redes sociais. Manda pro @bruno

Nicholas Romão Kneip
http://linkd.in/nrkneip

**Comment by annabida** [comment]
@marcaum-eth Before finalizing this issue, it is important to provide the official artwork for Arev, i.e. one artwork for each leader as listed below:
1. Grupo de Stellar - Líderes - Joaquin Soza e Francisco Catrileo
2. Grupo de Rust (EN) - Líder - @danicuki | W3D
3. Grupo Tokenomics - Líder - @Tiago Cavazin | W3D
4. Grupo DeFi Strategies - Líderes - Nicholas | W3D e Alexandre
5. Grupo de Blockchain - Líder - @Vini Black | W3D 
6. Grupo de DAOs - Líder - @Anna Bida | W3D
7. Grupo de Rust (PT) - Líder - @danicuki | W3D
8. Grupo de Firebase - Líder - @Evelyn Mendes | W3D
9. Grupo de Solidity - Líder - @Valter Lobo | W3D
10. Grupo Segurança para Smart Contracts - Líder - @Nosferas - Eduardo


We also suggest some adjustments to the artwork:
* Reduce the number of students to make the art cleaner and less cloying.
* Diversify the students from one image to another
* The template for classes with two leaders is also missing.

**Comment by marcaumdesign** [comment]
### Tecnologia

- [ ] Stellar
- [ ] ~Polkadot~

### Blockchain

- [x] Tokenomics
- [ ] DeFi Strategies
- [ ] DAOs
- [ ] Blockchain

### Desenvolvimento

- [ ] FIREBASE
- [ ] RUST EN
- [ ] RUST PT
- [ ] SOLIDITY
- [ ] Segurança para Smart Contracts

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/534900e0-1bba-4574-8186-7afc91e21a23)

**Comment by piadascripto** [comment]
Acho q a categorização não tá mto boa não. Polkadot e Rust é o mesmo grupo
de estudos…

**Comment by annabida** [comment]
@piadascripto um comentário antes perceba que listei todos os grupos de estudos com seus respectivos líderes.
@marcaum-eth achei que iamos ser mais minimalistas nas artes, reduzir o volume de students para não ficar enjoativo nas páginas... me surpreeendi com a direção que a arte seguiu.

**Comment by annabida** [comment]
@marcaum-eth we also need to consider groups that have two leaders, the template needs to have two featured photos.

**Comment by annabida** [comment]
@marcaum-eth atualizei o checklist que faltava a turma Blockchain, Rust são em dois idiomas, a palavra Strategies no grupo de DeFi e tbm risquei o Polkadot (pois não temos um grupo de estudos de polkadot, teremos na verdade um build/bootcamp. Veja a relação nos seguintes links:
* Grupos de estudos: https://build.w3d.community/study-groups
* Builds: https://build.w3d.community/courses

**Comment by annabida** [comment]
@marcaum-eth vou deixar o link do figma aqui para facilitar o acesso e registrar o histórico: https://www.figma.com/design/HbnwfL04JWwkvJuCEGowmv/UI-Design?node-id=0-1&t=n4szVWYOfnUQqWX3-0
