### ISSUE TITLE
Get students profile picture from Group Study

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/community-management#148]

**Comment by nomadbitcoin** [comment]
Here is all the images downloaded (30 students) https://drive.google.com/drive/folders/1GlGiZXuZccAi71a1fvUGLGqDf9Mnr5S3?usp=drive_link

**Comment by marcaumdesign** [comment]
Awesome, thanks!

**Comment by piadascripto** [comment]
Kind reminder that we need consent to use people’s pictures. @karla has the
contract.

Additionally, from now on we can have a version of this consent in our
website’s terms and condition to avoid handling multiples contracts with
community members

**Comment by nomadbitcoin** [comment]
Marked as completed in the presence of @marcaum-eth , @annabida  and @piadascripto
