### ISSUE TITLE
Harmonize Whatsapp groups

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#159]
Previous file: https://www.canva.com/design/DAFISgg9gZs/VYphktTy2hmmlIgntMiCKg/edit

**Comment by marcaumdesign** [comment]
Hey there, Anna! Just close the visual part for this issue, would like to ask: What meaning you gave for each color on those groups?

**Comment by annabida** [comment]
* Purple background - Enthusiast groups
* Blue background - Education groups
* Green background - Content groups and Builders
* Colored logo - More general groups
* Black background - Leadership
