### ISSUE TITLE
Send direct messages to members on twitter via Orbit

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#7]
Use Orbit's native auutomation to get more engagement with community members.

**Comment by annabida** [comment]
![](https://cdn.discordapp.com/attachments/1034941899917754498/1184213911638134885/image.png?ex=658b2826&is=6578b326&hm=d167f9d1bf80d4fb7d089c53206bbbe1d359952eea14eb615c6415a88a79954d&)

**Comment by viniblack** [comment]
It's blocked because in our current plan we can't do it, we'd have to upgrade the orbit plan.
