### ISSUE TITLE
Branding diagnosis

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#92]
## Description

We are seeking a comprehensive diagnosis of our brand to assess how it is perceived both internally and externally. This analysis is essential to ensure that our visual identity and messaging align with the values and goals of the WEB3DEV community.

**Comment by marcaumdesign** [comment]
# Overview

[Click here to open full diagnosis
](https://www.figma.com/board/XXp3BbPt8XUiB0cjsKBD7m/Diagn%C3%B3stico?node-id=77%3A1243&t=rSmZETIPXSo2vE30-1)

A branding diagnosis was executed on all channels of the Web3Dev: Instagram, X, YouTube, LinkedIn, Blog and Discord. 

The result was the construction of a Brand Book.

> Required by: @piadascripto

**Comment by piadascripto** [comment]
Thanks for the work @marcus.
One thing that annoys me quite a lot is the usage of “W3D” as a short logo
as well. We should stop using it as soon as possible to create a
consistence of our brand.
