### ISSUE TITLE
File review and permissions - Drive

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#93]
We need to conduct a detailed review of files and access permissions on our storage and design platforms, specifically Google Drive and Canva. This task is crucial to ensure that our documents and designs are efficiently organized and that only authorized individuals have access to them.

The details of this action can be found in the following file: https://docs.google.com/document/d/19ymFbhIpjFdNCfopAQ53GlkbTffLUF_Vo_qoV25Ppdg/edit

**Comment by yandosdados** [comment]
Please add me

**Comment by annabida** [comment]
@allluz and I met three times to rename folders, archive backups and outdated documents, delete duplicates and review access permissions on folders.
