### ISSUE TITLE
Create boards on Github

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#95]
## Description:

We need to set up project management boards on GitHub to streamline our workflow and improve task tracking and collaboration within the WEB3DEV community. This includes creating appropriate columns and managing access permissions.

### Board Creation:

- [x] Set up new project boards for different ongoing initiatives and projects.
- [x] Create columns that represent different stages of task progress (e.g., To Do, In Progress, Review, Done).
- [x] Write proper descriptions for all fields, stages and board readme.
- [x] Use template to create boards for current teams.

### Access Management:

- [x] Set up and manage access permissions to ensure that only authorized members can view and edit the boards.
- [x] Assign appropriate roles (e.g., read-only, write access) to members based on their responsibilities.
- [x] Document any changes made to access permissions and ensure they are communicated clearly to the team.

## Requirements:

- Experience with GitHub project management features.
- Strong organizational skills and attention to detail.
- Ability to communicate clearly and create comprehensive documentation.
- Familiarity with the community’s workflow and needs.

**Comment by annabida** [comment]
## [Consider Mapping Collaboration Activities](https://docs.google.com/spreadsheets/d/11I0WoU5MMtMR-Y4yW0XKGAqP12ANQgtxhbLMZgDmr-Q/edit#gid=713592544)

**Comment by nomadbitcoin** [comment]
Templates at #98

**Comment by marcaumdesign** [comment]
Really liked the way you organized and classified all the proprieties of the issues, seems super natural and ideal for such style of project! 🎉👏
