### ISSUE TITLE
Proposal for New UI Design for Our Build Platform

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/community-management#96]
We need a new user interface (UI) design for our build platform available at [build.w3d.community](https://build.w3d.community/). 

The new user interface design should include the following features that are currently not available:
- Support for multiple languages (Portuguese, English, and Spanish).

This proposal aims to enhance accessibility and user experience on our platform. 

### Design Requirements
- Create wireframes and mockups for the new UI.
- Provide design assets and guidelines for developers to implement the design.
- Ensure that the design is responsive and works well on different devices and screen sizes.

**Comment by annabida** [comment]
These materials can help you move forward: https://drive.google.com/drive/folders/1yTeIF-bQmcLUs8I6cLFodGzahMKH1g52

**Comment by marcaumdesign** [comment]
Salve, @piadascripto and @danicuki, como vão?

Criei aqui essa proposta de tela e gostaria de saber o que vocês acham da direção.

Abaixo tem um vídeo falando mais um pouco, e seria interessante que vocês assistissem.

https://github.com/w3b3d3v/community-management/assets/146405199/1d1492c8-bc74-4667-b79f-9e8fa731f613

Comentem nessa issue mesmo, que iremos fechar e guardar a resposta de vocês para quando começarmos a desenhar o projeto mais profundamente após a conclusão do Brand Book.

Abraços,
Marcus

**Comment by piadascripto** [comment]
SWAP: Não consigo enxergar um motivo, para ter um SWAP na plataforma de estudos. 
TRANSAÇÕES: Tb não consigo enxergar um motivo para isso. 

O desgin em si esta longe de ser algo pronto, pela diagramação do menu, pela duplicidade do logo sem motivo.. Os botão sem padding ficam ruins tb. 

Uma coisa que temos q fazer é perguntar ao cliente oq ele quer. Não jogar features no design… Antes de ver as telas queria ver o fluxo da usabilidade. Quais as paginas o usuário vai passar, qual a principal ação o usuário vai fazer?

Ter modo claro ou escuro é outra coisa q retiraria, não vejo motivo para gastar tempo com isso.

**Comment by piadascripto** [comment]
Queria tb ver consistência com o desgin do site q vem por ai…Vejo elementos diferentes, diagramção diferente. Temos q ter o site consistente com a plataforma de builds
