### ISSUE TITLE
Refinement of Discord Server

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/community-management#97]
Review and refine all channels on our Discord server. This includes:

- Images: Ensure all channel images are consistent with our brand.
- Buttons: Standardize button designs and functionality.
- Texts: Review and edit all text to maintain a unified tone and style.

The goal is to create a cohesive experience that aligns with our brand and the standards of our other platforms.

### Requirements
- Conduct a comprehensive review of all channels, roles, permissions, and overall server structure on the Discord server.
- Update images, buttons, and texts to reflect our brand's visual and stylistic standards.
- Ensure that the user experience is consistent and engaging.
- Collaborate with the marketing team to align with brand guidelines.

This task is essential to enhance the overall user experience and ensure brand consistency across our platforms.

**Comment by annabida** [comment]
@marcaum-eth Here's how the banner appears on the community entry page, after clicking on the Discord invite link (https://discord.com/invite/UXDUzG2hhE)

![Image](https://github.com/w3b3d3v/community-management/assets/97850972/30cdf67b-e525-4ee7-8e38-41c8f232b487)

The logo in the right corner is cut off for me (I use a macbook)

**Comment by annabida** [comment]
Here are the channels that contain images:
* start-here - https://discord.com/channels/898706705779687435/1192603669443641468
* choose-your-group - https://discord.com/channels/898706705779687435/1037389481482932244
* how-to-join - https://discord.com/channels/898706705779687435/1110017328009187358

**Comment by marcaumdesign** [comment]
Delivery

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/1d7ec608-f895-4f85-a7b9-cf3c91a4fd9c)

**Comment by marcaumdesign** [comment]
All images uploaded on our [Google Drive](https://drive.google.com/drive/folders/15MIYymyRyPxvGjQZS-0jiiBFGCJDaqq5?usp=drive_link)

**Comment by marcaumdesign** [comment]
Hey there, @annabida

What we need to close this issue?

**Comment by marcaumdesign** [comment]
aqui está a imagem @annabida, vou fechar aqui direto blz?

![Image](https://github.com/w3b3d3v/community-management/assets/146405199/b236bfab-d9ed-4a0e-946e-db72bd30813e)
